packaging: setup: remove problematic import
Previously the setup.py imported `lona.VERSION_STRING` to use in the setup
call of setuptools. The idea behind this import was to make the current version
number unique and reusable across the project.

Discord user @iluga (Coffee Cup) reported this stacktrace while installing
Lona:

    MYPATH>pip install lona
    Collecting lona
      Using cached lona-1.10.5.tar.gz (73 kB)
      Preparing metadata (setup.py) ... error
      error: subprocess-exited-with-error

      × python setup.py egg_info did not run successfully.
      │ exit code: 1
      ╰─> [14 lines of output]
          Traceback (most recent call last):
            File "<string>", line 2, in <module>
            File "<pip-setuptools-caller>", line 34, in <module>
            File "MYPATH\AppData\Local\Temp\pip-install-fdxen97y\lona_b81e6d87826c4ff1bf7fca84629770f8\setup.py", line 6, in <module>
              from lona import VERSION_STRING
            File "MYPATH\AppData\Local\Temp\pip-install-fdxen97y\lona_b81e6d87826c4ff1bf7fca84629770f8\lona\__init__.py", line 6, in <module>
              from .app import LonaApp
            File "MYPATH\AppData\Local\Temp\pip-install-fdxen97y\lona_b81e6d87826c4ff1bf7fca84629770f8\lona\app.py", line 15, in <module>
              from lona.command_line.run_server import run_server
            File "MYPATH\AppData\Local\Temp\pip-install-fdxen97y\lona_b81e6d87826c4ff1bf7fca84629770f8\lona\command_line\run_server.py", line 10, in <module>
              from lona.shell.shell import generate_shell_server, embed_shell
            File "MYPATH\AppData\Local\Temp\pip-install-fdxen97y\lona_b81e6d87826c4ff1bf7fca84629770f8\lona\shell\shell.py", line 1, in <module>
              from rlpython import embed
          ModuleNotFoundError: No module named 'rlpython'
          [end of output]

      note: This error originates from a subprocess, and is likely not a problem with pip.
    error: metadata-generation-failed

    × Encountered error while generating package metadata.
    ╰─> See above for output.

    note: This is an issue with the package mentioned above, not pip.
    hint: See above for details.

The setup.py seems to crash because a ModuleNotFoundError raises while
importing `lona.VERSION_STRING`. The missing module seems to be `rlpython`, a
dependency of Lona. The script assumes that all dependencies are installed
before the script runs. This assumption seems to be incorrect in some cases.

This import caused problems multiple times in the past, and its benefits do not
justify the packaging problems. Therefor this patch removes it.

Signed-off-by: Florian Scherf <mail@florianscherf.de>