view: _await_sync: fix TypeError on Python 3.11
Previously, `lona.View._await_sync()` passed coroutines into `asyncio.wait()`
to await them synchronously. This is forbidden since Python 3.11, and results
in a TypeError:

    LonaRuntimeWorker_0            ERROR    12:33:16.580011 lona.view_runtime Exception raised while running <__main__.Index object at 0x7f4bcd60c210>
      Traceback (most recent call last):
        File "/home/fscherf/devel/lona/lona/view_runtime.py", line 345, in start
          return_value=self.view.handle_request(self.request),
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/home/fscherf/devel/lona/doc/content/tutorial/02-html/example-2.py", line 35, in handle_request
          self.sleep(1)
        File "/home/fscherf/devel/lona/lona/view.py", line 304, in sleep
          return self._await_sync(asyncio.sleep(delay, result))
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/home/fscherf/devel/lona/lona/view.py", line 101, in _await_sync
          ).result()
            ^^^^^^^^
        File "/home/fscherf/.pyenv/versions/3.11.1/lib/python3.11/concurrent/futures/_base.py", line 456, in result
          return self.__get_result()
                 ^^^^^^^^^^^^^^^^^^^
        File "/home/fscherf/.pyenv/versions/3.11.1/lib/python3.11/concurrent/futures/_base.py", line 401, in __get_result
          raise self._exception
        File "/home/fscherf/devel/lona/lona/view.py", line 79, in await_awaitable
          finished, pending = await asyncio.wait(
                              ^^^^^^^^^^^^^^^^^^^
        File "/home/fscherf/.pyenv/versions/3.11.1/lib/python3.11/asyncio/tasks.py", line 415, in wait
          raise TypeError("Passing coroutines is forbidden, use tasks explicitly.")
      TypeError: Passing coroutines is forbidden, use tasks explicitly.

This patch adds a check to `lona.View._await_sync()` if a given awaitable is a
bare coroutine, and if so converts it to a asyncio task, which is recommended
by the documentation and the TypeError message it-self.

	https://docs.python.org/3/library/asyncio-task.html#waiting-primitives

Signed-off-by: Florian Scherf <mail@florianscherf.de>