client: dom updater: fix variable name
`_set_node()` requires a variable named `target_node_id`, not `node_id`.

Without this patch this exceptions raises when a node gets its child nodes
reinitialized:

    ReferenceError: node_id is not defined
        at LonaDomUpdater._set_node (http://localhost:8080/static//_lona/dom-updater.js:204:51)
        at LonaDomUpdater._apply_patch_to_child_nodes (http://localhost:8080/static//_lona/dom-updater.js:538:18)
        at LonaDomUpdater._apply_patch (http://localhost:8080/static//_lona/dom-updater.js:568:18)
        at http://localhost:8080/static//_lona/window.js:264:39
        at Array.forEach (<anonymous>)
        at LonaWindow._show_html (http://localhost:8080/static//_lona/window.js:257:18)
        at LonaWindow._handle_websocket_message (http://localhost:8080/static//_lona/window.js:374:22)
        at LonaWindow.handle_websocket_message (http://localhost:8080/static//_lona/window.js:394:25)
        at WebSocket._handle_raw_websocket_message (http://localhost:8080/static//_lona/context.js:254:25)

Signed-off-by: Florian Scherf <mail@florianscherf.de>